### ISSUE TITLE
No module named 'denite'

### ISSUE THREAD

**Issue by zanglg** [voldikss/vim-floaterm#44]
Thanks for the excellent plugin.

When I update my remote plug use cmd: UpdateRemotePlugins, I got a error message:

Encountered ModuleNotFoundError loading plugin at /Users/zang/.config/nvim/plugged/vim-floaterm/rplugin/python3/denite_f
loaterm.py: No module named 'denite'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/host.py", line 171, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 234, in lo
ad_module
    return load_source(name, filename, file)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 171, in lo
ad_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
ModuleNotFoundError: No module named 'denite'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /Users/zang/.local/share/nvim/rplugin.vim

So, how can I solve it, thanks.

**Comment by voldikss** [comment]
Have you installed denite.nvim plugin? (https://github.com/Shougo/denite.nvim)

**Comment by delphinus** [comment]
@zanglg I think this was already solved by #39. Use the latest master.

(You need not to install denite.nvim to solve this, probably.)

**Comment by zanglg** [comment]
@voldikss @delphinus 
Thanks, I have tried the lastest master, it was already solved.
